version: '3'

services:
  dev:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: llama
    container_name: llama
    volumes:
      - ../src:/app/src
    working_dir: /app
    tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
