services:
  chatbot:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: chatbot
    container_name: chatbot
    volumes:
      - ../src:/workspace/src
      - ../models:/workspace/models
      - ../documents:/workspace/documents
    working_dir: /workspace
    tty: true
    ports:
      - "7860:7860"
    environment:
      - PYTHONPATH=/workspace/src/modules
      - OPENAI_API_BASE=http://ollama:11434
      - OPENAI_API_KEY=dummy_api_key
    entrypoint: sh -c "cd /workspace/src && python gradio_app.py"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
